Attempt to fix Module naming style
dotnet/roslyn pull request #47242
Opened 2020-08-28 19:23 UTC by Youssef1313

Related to https://github.com/dotnet/roslyn-analyzers/pull/4086#discussion_r479483657
cc: @mavasani

2020-08-28 19:23 UTC, Youssef1313 commented
Marking as a draft as I think this needs additional changes to fix the issue.

2020-08-28 20:12 UTC, Youssef1313 commented
@mavasani In https://github.com/dotnet/roslyn/blob/master/src/Analyzers/VisualBasic/Tests/NamingStyles/NamingStylesTests.vb, all VB tests contain a PascalCase module. Not sure what's wrong. Also, I'm not sure how to continue with explicitly supporting "Module" in editorconfig.

2020-08-28 20:18 UTC, Youssef1313 commented
Alright, I've just seen your comment https://github.com/dotnet/roslyn-analyzers/pull/4086#discussion_r479493125.
However, I think Module is still not configurable in .editorconfig without this PR.

2020-08-28 20:36 UTC, Youssef1313 commented
Expecting the following tests to fail after adding the missing resource:

https://github.com/dotnet/roslyn/blob/163404b1385780bee5fc8a19a9ffc8ca44fdb773/src/VisualStudio/Core/Test/Options/BasicEditorConfigGeneratorTests.vb#L19

https://github.com/dotnet/roslyn/blob/163404b1385780bee5fc8a19a9ffc8ca44fdb773/src/VisualStudio/Core/Test/Options/CSharpEditorConfigGeneratorTests.vb#L18

2020-09-14 09:04 UTC, Youssef1313 commented
@mavasani Can you give this a look?
This PR is to support a VB Module naming preference. Currently it doesn't seem to be supported:

https://github.com/dotnet/roslyn/blob/7fa4e05dcf9be5472ce9ed00fe41a19c223eb348/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs#L64-L79

Do you want to support it? If yes, how I should move forward with this? If not, you can close.

2020-09-14 14:32 UTC, mavasani commented
@Youssef1313 Can you please add tests to show what is missing?

2020-09-14 16:00 UTC, Youssef1313 commented
@mavasani I'm not sure where the tests should go, but basically what I'm trying to do is support something like:

```ini
dotnet_naming_symbols.module.applicable_kinds = module # VB-specific.
```

I'm not sure whether you currently make modules follow the same rules for classes, or they're just always unchecked.

2020-10-15 15:46 UTC, mavasani commented
@Youssef1313 Will you be able to add tests to https://github.com/dotnet/roslyn/blob/master/src/Analyzers/VisualBasic/Tests/NamingStyles/NamingStylesTests.vb?

2020-10-16 20:48 UTC, Youssef1313 commented
@mavasani This is the scenario I'm trying to fix here:

![image](https://user-images.githubusercontent.com/31348972/96307294-aee22500-1001-11eb-8f63-6bd72ae60b77.png)

2020-10-16 20:54 UTC, Youssef1313 commented
From [Kind of symbols](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/naming-rules#kinds-of-symbols) section in docs, modules doesn't seem to be supported.

There are 2 solutions:

1. Support it as a separate symbol, which is what I was trying to do in this PR (but didn't work until now)
2. Make its style the same as whatever set for classes.

2022-02-08 21:08 UTC, sharwell requested changes
❓ Why would we not want this covered by `class`?

2022-02-09 10:38 UTC, Youssef1313 commented
@sharwell Yeah this should be the desired behavior and the fix should be easy enough, but the 1-year-ago me was stuck on such a trivial fix 😄

2022-02-09 10:43 UTC, Youssef1313 commented on src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs
> +                        builder.Add(_module);
@sharwell @mavasani Can you take a look please? Thanks!

2022-04-10 11:43 UTC, Youssef1313 commented on src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/Serialization/SymbolSpecification.cs
> +            }
This is a bad change, I think. It resulted from the tests creating `SymbolSpecification`s themselves, and not relying on the parser. Either tests should use the parser, or the following is updated to include modules:

https://github.com/dotnet/roslyn/blob/3e091aba2b46f8574c41f8431dcbeba42274ca86/src/EditorFeatures/DiagnosticsTestUtilities/NamingStyles/NamingStylesTestOptionSets.cs#L129-L136

2022-06-25 17:15 UTC, Youssef1313 commented
Replaced with https://github.com/dotnet/roslyn/pull/62141

2022-06-25 17:15 UTC, closed without merging