loccheckin
dotnet/roslyn pull request #47532
Opened 2020-09-08 19:25 UTC by cristianosuzuki77

Latest loc string and fixes for the following translation tickets:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1163530
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1180932
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1178477
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1180932
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1174024

This PR replaces https://github.com/dotnet/roslyn/pull/47474 with an additional fix (1174024)

2020-09-09 00:32 UTC, JoeRobich requested changes
@cristianosuzuki77 & @wli3 I didn't work through the entire set of string changes, but many translated strings are adding `.` when they are not present in the source string. Is this expected?

2020-09-09 00:32 UTC, JoeRobich commented on src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.de.xlf
> +        <target state="translated">"typeof" kann in "nameof" konvertiert werden.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">"typeof" kann in "nameof" konvertiert werden</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ko.xlf
> +        <target state="translated">'typeof'를 'nameof'로 변환할 수 있습니다.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">'typeof'를 'nameof'로 변환할 수 있습니다</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Analyzers/CSharp/Analyzers/xlf/CSharpAnalyzersResources.ru.xlf
> +        <target state="translated">"typeof" можно преобразовать в "nameof".</target>
Original string did not include a `.`
```suggestion
        <target state="translated">"typeof" можно преобразовать в "nameof"</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Analyzers/VisualBasic/Analyzers/xlf/VisualBasicAnalyzersResources.de.xlf
> +        <target state="translated">"GetType" kann in "NameOf" konvertiert werden.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">"GetType" kann in "NameOf" konvertiert werden</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Analyzers/VisualBasic/Analyzers/xlf/VisualBasicAnalyzersResources.ko.xlf
> +        <target state="translated">'GetType'을 'NameOf'로 변환할 수 없습니다.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">'GetType'을 'NameOf'로 변환할 수 없습니다</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Analyzers/VisualBasic/Analyzers/xlf/VisualBasicAnalyzersResources.ru.xlf
> +        <target state="translated">"GetType" можно преобразовать в "NameOf".</target>
Original string did not include a `.`

```suggestion
        <target state="translated">"GetType" можно преобразовать в "NameOf"</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
> +        <target state="translated">&amp; pro skupiny metod se nedá použít ve stromech výrazů.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">&amp; pro skupiny metod se nedá použít ve stromech výrazů</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
> +        <target state="translated">Operátor {0} je na operandech {1} a {2} nejednoznačný.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">Operátor {0} je na operandech {1} a {2} nejednoznačný</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
> +        <target state="translated">Asynchronní příkaz foreach nejde použít pro proměnné typu {0}, protože {0} neobsahuje vhodnou veřejnou definici instance nebo rozšíření pro {1}.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">Asynchronní příkaz foreach nejde použít pro proměnné typu {0}, protože {0} neobsahuje vhodnou veřejnou definici instance nebo rozšíření pro {1}</target>
```

2020-09-09 00:32 UTC, JoeRobich commented on src/Compilers/CSharp/Portable/xlf/CSharpResources.cs.xlf
> +        <target state="translated">Přístupový objekt init není platný pro statické členy.</target>
Original string did not include a `.`

```suggestion
        <target state="translated">Přístupový objekt init není platný pro statické členy</target>
```

2020-09-09 05:18 UTC, wli3 commented
@cristianosuzuki77?

2020-09-09 21:24 UTC, cristianosuzuki77 commented
Checking with translators.

2020-09-15 19:02 UTC, wli3 commented
@cristianosuzuki77 ping. Any update?

2020-09-18 16:28 UTC, cristianosuzuki77 commented
The translators confirmed instances of where the dots were introduced are not correct. A new pull request will be created.
Root cause analysis as well is undergo.

2020-09-23 05:02 UTC, wli3 commented
@cristianosuzuki77 where is the new PR? It has been several weeks for getting back and forth for this issue, is there an ETA? The VS loc deadline is coming soon.

2020-09-23 20:15 UTC, cristianosuzuki77 commented
Should be in tomorrow.

2020-09-24 16:14 UTC, cristianosuzuki77 commented
Today's PR is still showing up few spots with the extra dot. Translation team says it is expected, but I am asking them to clarify before proceeding. ETA is pushed to tomorrow.

2020-09-24 23:51 UTC, cristianosuzuki77 commented
Addressing this via https://github.com/dotnet/roslyn/pull/48037

2020-09-24 23:51 UTC, closed without merging