Disable document rename for razor mapped files
dotnet/roslyn pull request #48167
Opened 2020-09-29 20:27 UTC by dibarbet

Resolves https://github.com/dotnet/roslyn/issues/46580

2020-09-29 21:20 UTC, ryzngard commented on src/Workspaces/Core/Portable/Rename/Renamer.cs
> +            if (document.Services.GetService<ISpanMappingService>() != null)
Can we add a test for this in [RenamerTests](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces.UnitTests/Renamer/RenamerTests.cs,d3fdb62c67de81fe)?

2020-09-29 21:20 UTC, ryzngard requested changes
Glad the fix was easy. Needs a test

2020-09-29 22:22 UTC, ryzngard approved these changes

2020-09-30 00:45 UTC, merged

2020-09-30 05:47 UTC, jinujoseph commented
@NTaylorMullen this has been merged !