Correct IsImplicitlyDeclared for SimpleProgramNamedTypeSymbol
dotnet/roslyn pull request #48176
Opened 2020-09-29 23:05 UTC by Youssef1313

The class documentation clearly states:

```csharp
    /// <summary>
    /// Represents implicitly declared type for a Simple Program feature.
    /// </summary>
```

Fixes #48171

2020-09-29 23:14 UTC, CyrusNajmabadi commented
Needs tests :)

2020-09-30 01:47 UTC, AlekseyTs commented on src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs
> +        public override bool IsImplicitlyDeclared => true;
>public override bool IsImplicitlyDeclared => true; [](start = 8, length = 50)

This is not a change that we would like to make. Please revert

2020-09-30 01:48 UTC, AlekseyTs requested changes
This isn't a change that we would want to make.

2020-09-30 01:53 UTC, AlekseyTs commented
@Youssef1313 In the future, especially for bugs that require changes in compilers, please make sure that:
- the problem in the bug has been stated in compiler terms (i.e. some API returns unexpected value, etc)
- the bug has been triaged and that we confirmed that we would like to make the suggested change

2020-09-30 01:53 UTC, closed without merging

2020-09-30 09:47 UTC, Youssef1313 commented
> 
> 
> This isn't a change that we would want to make.

Can you clarify why?

I can't see why the change is wrong. The [documentation for IsImplicitlyDeclared](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isymbol.isimplicitlydeclared?view=roslyn-dotnet) states:

> Returns true if this symbol was automatically created by the compiler, and does not have an explicit corresponding source code declaration.

And that's the case with the symbol `<Program>$` (i.e. SimpleProgramNamedTypeSymbol). It is automatically created by the compiler and it's indeed doesn't have an explicit source code declaration.