Fix FAR counting for target-typed new
dotnet/roslyn pull request #48434
Opened 2020-10-08 13:07 UTC by Youssef1313

Fixes #47987

Counting implicit object creations was depending on whether the whole document **contains** any implicit object creations or not.
That caused normal object creations to count as implicit when the document contains implicit creations. So, the normal object creations were counted twice.

2020-10-08 13:10 UTC, Youssef1313 commented on src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs
> +                if (syntaxFacts.IsImplicitObjectCreation(node))
@jcouv In 

https://github.com/dotnet/roslyn/pull/43645/files#diff-aeace626a93e2448b1aec4bc466c9931R336-R337

I see you introduced an extension method called "IsImplicitObjectCreationExpression". So I'm not sure whether I should use `IsImplicitObjectCreation` instance method, or `IsImplicitObjectCreationExpression`, and why we need the two?

2020-10-08 13:46 UTC, Youssef1313 reviewed
The method `FindReferencesInImplicitObjectCreationExpressionAsync` is currently in `AbstractReferenceFinder.cs`. I think it makes more sense to move it as a private method to `ConstructorSymbolReferenceFinder.cs`.

I can't see a reason why to make it in `AbstractReferenceFinder` while its friend is in `ConstructorSymbolReferenceFinder`:

https://github.com/dotnet/roslyn/blob/bc85a40ac042f9cf799f5e43deb0fee2d595247b/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs#L107

If you agree, I'll fix that.

2020-10-08 13:49 UTC, Youssef1313 reviewed
Note 2:

`FindReferencesInImplicitObjectCreationExpressionAsync` currently returns a `Task`, while `FindOrdinaryReferencesAsync` returns a `ValueTask`.

I'm not sure if there is a performance benefit if both are returning a `ValueTask`. It worth having a look.

2020-10-08 13:57 UTC, sharwell commented
Blocked on #48401 that we are taking for 16.8

2020-10-08 14:26 UTC, sharwell commented
@Youssef1313 No we can keep the test in the master branch. I was fixing a performance issue for 16.8 and it just happens to have the same root cause as this.

2020-10-08 14:40 UTC, Youssef1313 commented
> No we can keep the test in the master branch.

@sharwell Thanks. I'm keeping it in master.

There does seem to be test failures here related to the FAR feature. Can you please re-run the failed job to see whether it's a consistent failure or just flaky?

I can't currently debug this because of some weird errors I'm getting in Visual Studio:

![image](https://user-images.githubusercontent.com/31348972/95473860-ce83a880-0984-11eb-9056-6715ffac1b4a.png)

I tried to restart Visual Studio a couple of times, but every time I just get a different weird error.

2020-10-08 15:44 UTC, CyrusNajmabadi commented
Already has PR to fix in: https://github.com/dotnet/roslyn/pull/48402 :)

2020-10-08 15:45 UTC, CyrusNajmabadi requested changes
Thanks for the PR, however this is something Sam and I already have fixes for.  https://github.com/dotnet/roslyn/pull/48402

Sorry for any time wasted.

2020-10-08 15:48 UTC, Youssef1313 commented
@CyrusNajmabadi No problem at all! Closing as duplicate.

2020-10-10 15:46 UTC, Youssef1313 commented
The bug is already fixed, but I re-opened to add the test to prevent regressions while refactoring in the future.

2020-10-10 15:55 UTC, Youssef1313 commented
> Blocked on #48401 that we are taking for 16.8. Keeping this PR open since the test is still helpful.

@sharwell This is no longer blocked as your PR is now merged..

2020-10-10 17:09 UTC, sharwell approved these changes

2020-11-04 13:28 UTC, Youssef1313 commented
@CyrusNajmabadi This is a test only change. Can you please review?

2020-11-08 18:45 UTC, sharwell approved these changes

2020-11-08 18:46 UTC, merged