Make GreenNode.CreateList static
dotnet/roslyn pull request #48536
Opened 2020-10-12 21:47 UTC by HurricanKai

As discussed with @CyrusNajmabadi on [discord] (https://discord.com/channels/143867839282020352/598678594750775301/765314698261692428) this PR makes GreenNode.CreateList static and adjusts all usages.

2020-10-12 21:47 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=48536) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=48536) before we can accept your contribution.<br/><br/>:x: HurricanKai [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=48536)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn?pullRequest=48536) it.</sub>

2020-10-12 22:18 UTC, CyrusNajmabadi approved these changes

2020-10-12 22:43 UTC, 333fred commented on src/Compilers/Core/Portable/Syntax/SyntaxList`1.cs
> +            var newGreen = GreenNode.CreateList(items.Select(n => n.Green));
It looks like `cretor` is also unused now. We should remove these unecessary parameters all the way up the tree.

2020-10-12 22:44 UTC, 333fred requested changes
Done review pass (commit 1)

2020-10-13 14:33 UTC, CyrusNajmabadi approved these changes

2020-10-13 14:42 UTC, CyrusNajmabadi commented
@dotnet/roslyn-compiler can we get a second pair of eyes on this nice community PR? :)

2020-10-13 17:37 UTC, 333fred approved these changes
LGTM (commit 4). @dotnet/roslyn-compiler for a second review. There are no perf numbers in this PR, but Kai is planning on submitting a second PR that actually refactors the implementation of `GreenNode.CreateList` that removes a bunch of double-allocations that should have a big impact, and this first change will simplify that.

2020-10-13 17:40 UTC, CyrusNajmabadi commented
> There are no perf numbers in this PR,

True.  Though changing these virtual methods (and extra parameters and whatnot) to just static calls, should be pure benefit.  At worse, we should have no perf change.  A best, potentially some uptick :)

2020-10-13 18:14 UTC, cston approved these changes

2020-10-13 19:57 UTC, merged

2020-10-13 19:58 UTC, 333fred commented
Thanks @HurricanKai!