Slightly delay inline tags so that they don't immediately appear when user it typing a longer shortcut.
dotnet/roslyn pull request #48881
Opened 2020-10-23 17:47 UTC by CyrusNajmabadi

A couple of people have mentioned that inline-tags appear as they're typing `ctrl-alt-some-other-char`.  This can be distracting/annoying/flashing.

I've tweaked things to put inline-hints on a slightly longer delay.  Manual testing here found adding a 100ms delay here struck a sweet spot of having these no longer appear when typing another shortcut, while still feeling like they come up quickly when you do want them.  

If this  isn't a suitable fix in practice, we can consider a different trigger chord that either isn't the prefix of other commands, or is only a prefix for a suitably tiny set of rare commands such that users will be very unlikely to see this.

This PR sholud be reviewed commit by commit.  The first commit is a rename for clarity.  The second introduces the new behavior.

2020-10-23 17:51 UTC, NTaylorMullen approved these changes

2020-10-23 18:25 UTC, sharwell commented
This is going to make the interference with multiple carets even worse ☹️

2020-10-23 18:30 UTC, sharwell commented on src/EditorFeatures/Core/InlineHints/InlineHintsDataTaggerProvider.cs
> +                TaggerEventSources.OnOptionChanged(subjectBuffer, InlineHintsOptions.DisplayAllOverride, TaggerDelay.NearImmediate),
💭 We really need this to start calculation on `Immediate` delay, but avoid rendering notification faster than `NearImmediate`. I've seen cases where calculation is not immediate and this delay can be used for latency hiding.

2020-10-23 18:33 UTC, sharwell requested changes
This change assumes that <kbd>Ctrl</kbd>+<kbd>Alt</kbd> is the trigger for this feature. However, this is already bound to multi-caret insertion, which is heavily mouse driven and cannot be impaired by a feature that moves characters around on the screen. Finding a new keyboard trigger for inline hints is required, and only after we identify the new shortcut will we know what the possible other interactions are.

2020-10-23 18:37 UTC, CyrusNajmabadi commented
Good point.  @olegtk @AmadeusW do you know if shift-space is used for anything?

2020-10-23 18:42 UTC, NTaylorMullen commented
> do you know if shift-space is used for anything?

Technically it enters a "space" today into the editor; however, if we were to change that I'd be psyched 😄

2020-10-23 18:46 UTC, sharwell commented
> Technically it enters a "space" today into the editor; however, if we were to change that I'd be psyched 😄

I'm going to guess a bunch of people use this to TYPE CAPITAL LETTERS IN COMMENTS.

2020-10-23 18:47 UTC, NTaylorMullen commented
> TYPE CAPITAL LETTERS IN COMMENTS.

BUT BUT BUT I WANT IT

2020-10-23 18:50 UTC, CyrusNajmabadi commented
> Technically it enters a "space" today into the editor; however, if we were to change that I'd be psyched 😄

It wouldn't change anything.  We never capture these keys.  We just use the signal that they're held down (for some amount of time) to trigger this.  So the user would have to be holding shift-spaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaace to have an issue here.  THat said, someone might be doing that... i.e. `NOW                 IS                THE               TIME`.  Not sure if that's an issue or not.

2020-10-23 18:52 UTC, CyrusNajmabadi commented
Nevermind.  shift-space is not usable at all in any evnet.  Because if someone just wants to see the inline hint, it would never be ok for that to insert space.

2020-10-25 04:50 UTC, CyrusNajmabadi commented
Closing out.  We sidestepped this by changing the keybinding to Alt-F1

2020-10-27 08:35 UTC, closed without merging