Fix 2 BC42108 warnings in Speculation SpeculationAnalyzer.VB
dotnet/roslyn pull request #50141
Opened 2020-12-27 03:21 UTC by paul1956

Also remove some extra whitespace in Doc Comment. via manual edits.

2020-12-27 03:54 UTC, CyrusNajmabadi approved these changes

2020-12-28 02:33 UTC, sharwell requested changes

2020-12-28 02:33 UTC, sharwell commented on src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Utilities/SpeculationAnalyzer.vb
> +            Dim newConversion As Conversion? = Nothing
These diagnostics are only reported in the IDE, as a result of a compiler bug. The underlying bug should be fixed instead of adding these.

2020-12-28 02:36 UTC, sharwell commented
Duplicate of #47282

2020-12-28 02:36 UTC, closed without merging