IVT Microsoft.VisualStudio.LanguageServerClient.Razor
dotnet/roslyn pull request #50970
Opened 2021-02-03 00:49 UTC by ryanbrandenburg

Specifically razor will soon need `IAsynchronousOperationListenerProvider` and it's descendants.

2021-02-03 00:53 UTC, sharwell requested changes
These types will need to be provided through types in an external access assembly, and not directly through IVTs. For example, `IApexAsynchronousOperationListenerProviderAccessor` provides Apex with access to the APIs it needs from `IAsynchronousOperationListenerProvider`. You'll want a `IRazorAsynchronousOperationListenerProviderAccessor` to provide the APIs needed by Razor.

2021-02-03 18:38 UTC, ryanbrandenburg commented
@sharwell the ExternalAccess pattern is a new one to me, clean if a little verbose. I assume the idea there just to put hard and explicit limits on which APIs get IVT'd?

2021-02-03 19:21 UTC, sharwell commented
> I assume the idea there just to put hard and explicit limits on which APIs get IVT'd?

It helps in two ways:

1. We know which partners are using which internal APIs
2. If we change an internal signature, we can update the wrapper to avoid breaking the partner (e.g. if we add a parameter, we can update the wrapper to pass a default value for that parameter instead of forcing the partner to update their use in a coordinated insertion)

2021-02-03 19:23 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/IRazorAsynchronousOperationListenerProviderAccessor.cs
> +        IAsynchronousOperationListener GetListener(string featureName);
```suggestion
        RazorAsynchronousOperationListenerWrapper GetListener(string featureName);
```

2021-02-03 19:24 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/IRazorAsynchronousOperationListenerProviderAccessor.cs
> +        IAsynchronousOperationListener GetListener(string featureName);
Here's another wrapper:

https://github.com/dotnet/roslyn/blob/master/src/Tools/ExternalAccess/Razor/Remote/RazorRemoteServiceCallbackIdWrapper.cs

You won't need the data contract attributes in this case, but the wrapper concept would be the same.

2021-02-03 21:12 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/IRazorAsynchronousOperationListenerProviderAccessor.cs
> +        IRazorAsynchronousOperationListener GetListener(string featureName);
💡 Use of an interface adds allocation overhead to this wrapper. Switching to a `readonly struct` will eliminate the overhead.

2021-02-03 21:18 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/RazorAsynchronousOperationListenerWrapper.cs
> +    internal class RazorAsynchronousOperationListenerWrapper
```suggestion
    internal readonly struct RazorAsynchronousOperationListenerWrapper
```

2021-02-03 22:01 UTC, ryanbrandenburg commented
/azp run

2021-02-03 22:01 UTC, ryanbrandenburg commented
\azp run

2021-02-04 19:38 UTC, sharwell approved these changes

2021-02-04 19:38 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/IRazorAsynchronousOperationListenerProviderAccessor.cs
> +#nullable disable
```suggestion
```

2021-02-04 19:38 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/RazorAsynchronousOperationListenerProviderAccessor.cs
> +            AsynchronousOperationListenerProvider implementation)
```suggestion
            IAsynchronousOperationListenerProvider implementation)
```

2021-02-04 19:47 UTC, sharwell commented on src/Tools/ExternalAccess/Razor/RazorAsynchronousOperationListenerProviderAccessor.cs
> +        private readonly AsynchronousOperationListenerProvider _implementation;
```suggestion
        private readonly IAsynchronousOperationListenerProvider _implementation;
```

2021-02-08 19:13 UTC, merged