Move todo comments to Editor Features
dotnet/roslyn pull request #51643
Opened 2021-03-03 22:45 UTC by davidwengier

FYI @Therzok 

There isn't much to this so I don't think its going to fundamentally fix anything in VS Mac, but we may as well prevent them having to copy the source code if there isn't a good reason to.

2021-03-03 23:13 UTC, CyrusNajmabadi commented
> Move todo comments analyzer to Editor Features 

Can this not be at the feature level?

2021-03-03 23:54 UTC, davidwengier commented
> > Move todo comments analyzer to Editor Features
> 
> Can this not be at the Features or even Workspace level? I don't see anything Editor specific about this (i.e. using buffers/views).

Updated. Cunningham's Law strikes again :)

2021-03-04 00:46 UTC, sharwell commented
@davidwengier Don't merge this yet. It was carefully constructed to silently disable itself if OOP gets turned off. I want to make sure that 1) we don't lose that and 2) we aren't running this analyzer in both processes at the same time.

2021-03-04 00:54 UTC, sharwell requested changes
I have no strong objection to trying to move `InProcTodoCommentsIncrementalAnalyzer` down to the Features layer, but there is a big remaining problem: `InProcTodoCommentsIncrementalAnalyzerProvider` is not exported (claimed by design), which means this move does not make TODO comments scanning any easier for external consumers. We need to either move `VisualStudioTodoCommentsService` or find a way to register the provider without breaking functionality.

2021-03-04 00:54 UTC, sharwell commented on src/EditorFeatures/CSharpTest/TodoComment/NoCompilationTodoCommentTests.cs
> +        public Task<ImmutableArray<CodeAnalysis.TodoComments.TodoComment>> GetTodoCommentsAsync(Document document, ImmutableArray<TodoCommentDescriptor> commentDescriptors, CancellationToken cancella
❔ Can this not be fixed with a using directive?

2021-03-04 01:50 UTC, davidwengier commented
@sharwell It's not clear to me why we need to do that before merging this PR, given that it wasn't a goal of this PR nor is made any more difficult by this PR.

2021-03-04 05:35 UTC, allisonchou commented
/azp run
(Going through open PRs since it looks like the master -> main transition made test running funky.)

2021-03-04 05:35 UTC, allisonchou commented
/azp run

2021-03-04 17:04 UTC, sharwell commented
@davidwengier It's not clear what the purpose of this pull request is. `AbstractTodoCommentsIncrementalAnalyzer` already lives in the features layer, and the changes proposed by this pull request do not align with the claim that it removes the need to implement these types separately (as the types are not exposed).

2021-03-04 21:49 UTC, davidwengier commented
> @davidwengier David Wengier FTE It's not clear what the purpose of this pull request is.

The purpose is solely to prevent VSMac having to source-copy the incremental analyzer and analyzer provider. It comes from a request [here](https://github.com/xamarin/vsmac/pull/2495#discussion_r511564161) if you have access.

> it's not desirable to adjust the code in ways that specifically facilitate increased use of APIs through IVTs.

I agree with the spirit of this comment, but when the alternative option is copying source code which then becomes stale, I think allowing the IVT is the objectively better choice. I think thats especially true for something like this which is a pure move. If I'd left the namespaces in tact in the files there would have been no code changes at all.

For good or bad VSMac has extensive use of IVTs and I don't feel that blocking individual PRs does anything other than make life harder for the VSMac team, or in some cases prevents them shipping software. There was a larger conversation around trying to move them to external access but it was ruled out because the scope is too large, and the resources too little.

2021-03-04 23:48 UTC, sharwell commented
In this case it seems desirable to keep the current form. When we do move the implementation, it should be moved and exposed only through an external access layer which VS Mac can use.

> There was a larger conversation around trying to move them to external access but it was ruled out because the scope is too large, and the resources too little.

This was the case when VS Mac agreed to handle breaking changes on their side as they arose, but it is proving to not be viable. VS Mac will need to transition to external access and progressively revoke the external IVTs so these problems do not continue in the future.

2021-03-05 02:13 UTC, davidwengier commented
Desirable to who? The VS Mac team have asked for it (that comment I linked to is an open PR on their end, refactoring their todo comment implementation) and yes this will break VS Mac, but i'm the one who fixes those breaks, so if you're blocking my PR in order to save me work, you may rest assured that I considered that in advance 😛

2021-03-09 00:15 UTC, jasonmalinowski approved these changes

2021-03-09 01:10 UTC, merged