Remove reliance on unreliable UpdateFile operation
dotnet/roslyn pull request #52441
Opened 2021-04-06 19:59 UTC by sharwell

The new code follows the approach of `AbstractEditorTest.SetUpEditor`.

2021-04-06 21:25 UTC, jasonmalinowski commented
What is making UpdateFile unreliable? Should we remove it?

2021-04-06 21:43 UTC, sharwell commented
> What is making UpdateFile unreliable

No idea. It's just a guess based on logs [like this](https://dev.azure.com/dnceng/public/_build/results?buildId=1073818):

```
System.AggregateException: One or more errors occurred. ---> System.Exception: Marker '/* 1 */' not found in text: using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestProj
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}

   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass8_0.<PlaceCaret>b__0(IWpfTextView view) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs:line 190
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass13_0.<GetExecuteOnActionViewCallback>b__0(CancellationToken cancellationToken) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs:line 257
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.<>c__DisplayClass6_0.<<InvokeOnUIThread>b__0>d.MoveNext() in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs:line 59
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.InvokeOnUIThread(Action`1 action)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.PlaceCaret(String marker, Int32 charsOffset, Int32 occurrence, Boolean extendSelection, Boolean selectBlock) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs:line 160
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
---> (Inner Exception #0) System.Exception: Marker '/* 1 */' not found in text: using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestProj
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}

   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass8_0.<PlaceCaret>b__0(IWpfTextView view) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs:line 190
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.TextViewWindow_InProc.<>c__DisplayClass13_0.<GetExecuteOnActionViewCallback>b__0(CancellationToken cancellationToken) in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/TextViewWindow_InProc.cs:line 257
   at Microsoft.VisualStudio.IntegrationTest.Utilities.InProcess.InProcComponent.<>c__DisplayClass6_0.<<InvokeOnUIThread>b__0>d.MoveNext() in /_/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs:line 59<---
```

![image](https://user-images.githubusercontent.com/1408396/113782029-666d0f80-96e6-11eb-9c8b-e4993237445b.png)

2021-04-07 01:43 UTC, jasonmalinowski requested changes
I guess if we think this is unsafe to use, then we should remove it and update tests. Or we don't have the evidence this is actually problematic then we should clarify the PR title accordingly.

2021-04-07 03:51 UTC, sharwell commented
@jasonmalinowski The code is used in three locations. This is the only location where tests in the last 30 days failed to achieve the desired outcome following the call. The issue has not been locally reproducible, and we have no evidence suggesting the reason why this call fails at this location. This pull request converts an operation which does not always produce the expected results (unreliable) to another form used elsewhere that does appear to produce the expected results.

2021-04-07 16:11 UTC, tmat approved these changes

2021-04-07 16:13 UTC, tmat commented
@jasonmalinowski I believe this addresses some of the issues reported in https://github.com/dotnet/roslyn/issues/52409

2021-04-07 18:23 UTC, jasonmalinowski approved these changes

2021-04-07 18:23 UTC, merged