Respect ReportSuppressedDiagnostics option for DiagnosticSuppressor
dotnet/roslyn pull request #53045
Opened 2021-04-30 01:42 UTC by safu9

This PR fixes #41584.

Diagnostics suppressed programatically by DiagnosticSuppressor were not excluded properly when ReportSuppressedDiagnostics option is set to true.

2021-05-05 06:21 UTC, safu9 commented
@sharwell @mavasani Could you review this PR?

2021-05-05 07:36 UTC, mavasani requested changes
This compilation option is not to determine whether or not diagnostic suppressors should run. The option indicates whether or suppressed diagnostics should be filtered out from final diagnostics output. Basically, this option is unrelated to suppressors.

2021-05-05 10:21 UTC, safu9 commented
I mentioned this in #52953.
This option works properly with many ways to suppress diagnostics such as `pragma warning disable` and `SuppressMessageAttribute`.
I think the only exception is DiagnosticSuppressor.
This option does not exclude diagnostics suppressed by DiagnosticSuppressor for now.

The current program executes following steps if this option is true.
1. List up all diagnostics and call this method. https://github.com/dotnet/roslyn/blob/2f20729b0b4bc78865fcc663aa4cf33323b723d3/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs#L1070
2. At line 1072, `FilterDiagnosticsSuppressedInSource` exclude suppressed diagnostics in source, which is fine.
3. At line 1073, `ApplyProgrammaticSuppressions` check whether each diagnostic is suppressed by DiagnosticSuppressor.

In 3rd step, `ApplyProgrammaticSuppressions` is expected exclude suppressed diagnostics, but they actually only set `Diagnostic.IsSuppressed` to true and return them.
I fixed this behaviour of `ApplyProgrammaticSuppressions` in this PR.
This PR doesn't prevent DiagnosticSuppressor from runnning.

2021-05-05 11:24 UTC, Youssef1313 commented
What I understand from the PR is that currently, ReportSuppressedDiagnostics isn't respected for DiagnosticSuppressors. However, I see DiagnosticSuppressor tests in roslyn-analyzers relying on ReportSuppressedDiagnostics property.

https://github.com/dotnet/roslyn-analyzers/blob/a534bf8c8310f375d163f701ade001e47ef55fb2/src/Roslyn.Diagnostics.Analyzers/UnitTests/RelaxTestNamingSuppressorTests.cs#L24

Not sure what's going on?

2021-05-05 13:39 UTC, sharwell approved these changes

2021-05-05 13:40 UTC, sharwell commented
I agree with the analysis in https://github.com/dotnet/roslyn/pull/53045#issuecomment-832579578. This oversight is the main reason we don't have any support for testing diagnostic suppressors in Microsoft.CodeAnalysis.Testing.

2021-05-05 21:05 UTC, Youssef1313 commented
> I agree with the analysis in [#53045 (comment)](https://github.com/dotnet/roslyn/pull/53045#issuecomment-832579578). This oversight is the main reason we don't have any support for testing diagnostic suppressors in Microsoft.CodeAnalysis.Testing.

FYI - I managed to write tests for suppressors before. https://github.com/dotnet/efcore/pull/24151/ (might not be the best way - but you may be able to use a similar idea for roslyn-sdk until this PR is merged and shipped)

2021-05-06 07:00 UTC, mavasani commented
The implementation in this PR is wrong, the filtering is done at the wrong place. Note that without your change, all programmatically suppressed diagnostics from suppressors will always go through the below code path and info diagnostics will be reported in binary logs for them, regardless of the value of this option: https://github.com/dotnet/roslyn/blob/a6b8bb581cac6b1016a45d1a50d96b60a0d584f1/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L560-L571

With your change, this will no longer be true when `ReportSuppressedDiagnostics` option is false. Note that **always** reporting these info diagnostics corresponding to diagnostics suppressed by suppressors was a **hard** requirement in the original design approval of suppressors. Without these info diagnostics in binlogs, end users would have no idea what caused their diagnostics to be suppressed.

The correct fix here would be to revert your changes and move out the filtering to be done just after the callsite inside `CompilationWithAnalyzers` to apply programmatic suppressions: https://github.com/dotnet/roslyn/blob/a6b8bb581cac6b1016a45d1a50d96b60a0d584f1/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L468

Also, please add unit tests for this change.

2021-05-06 07:07 UTC, Youssef1313 commented
@mavasani Wouldn't that make the method `FilterDiagnosticsSuppressedInSourceOrByAnalyzers` misleading? It won't be filtering anything by `DiagnosticSuppressor`s as the name suggests?

2021-05-06 08:04 UTC, mavasani commented
@Youssef1313 Naming is a minor thing for a private method. We cannot cause a functionality break for the most important requirement in the DiagnosticSuppressor design.

2021-05-06 08:14 UTC, Youssef1313 commented
@mavasani Yeah certainly. I meant that we could rename it as a minor cleanup.

2021-05-07 09:07 UTC, safu9 commented
@mavasani Thank you for the review. I'll fix the implementation of `CompilationWithAnalyzers`.

2021-06-09 18:00 UTC, safu9 commented
@mavasani I have rewrited the implementation and add some tests.
This should not change behaviour of `CommonCompiler`, and just fix `CompilationWithAnalyzers`.
`CommonCompiler` is using `AnalyzerDriver.ApplyProgramaticSuppressions`, so I revert its changes and added a new method to filter suppressed diagnostics.

2021-06-19 08:53 UTC, safu9 commented
@mavasani Could you re-review this?

2022-01-21 19:12 UTC, Youssef1313 commented
@mavasani Can you take a look please? Thanks!

2022-01-24 08:54 UTC, mavasani commented on src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
> +            return builder.ToImmutable();
```suggestion
            if (compilation.Options.ReportSuppressedDiagnostics || diagnostics.All(d => !d.IsSuppressed))
               return diagnostics;

            return diagnostics.WhereAsArray(d => !d.IsSuppressed);
```

2022-01-24 09:01 UTC, mavasani commented on src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs
> +            Assert.Empty(diagnostics);
This seems to be a redundant check. Code below from [line 319-322](https://github.com/dotnet/roslyn/pull/53045/files#diff-a0b279d58233deddedac1fca458609ef81a83be228dee99e39476ec043b5ff87R319-R322) already does this validation.
```suggestion
```

2022-01-24 09:02 UTC, mavasani commented on src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs
> +            Assert.Empty(diagnostics);
I mean the below existing code in `GetCompilationWithAnalyzerDiagnostics`:

```cs
            if (!reportSuppressedDiagnostics)
            {
                Assert.True(diagnostics.All(d => !d.IsSuppressed));
            }
```

2022-01-24 09:19 UTC, mavasani approved these changes
Looks good to me. I have couple of suggestions to further simplify the code changes.

2022-01-24 09:20 UTC, mavasani commented
@dotnet/roslyn-compiler for reviews

2022-02-07 18:36 UTC, cston commented on src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs
> +            if (compilation.Options.ReportSuppressedDiagnostics || diagnostics.All(d => !d.IsSuppressed))
>|| diagnostics.All(d => !d.IsSuppressed) [](http://example.com/codeflow?start=64&length=40)

Is this check necessary? (`WhereAsArray()` below will return the original array without allocations if all items satisfy the predicate.)

2022-02-08 04:45 UTC, safu9 commented on src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs
> +            // Verify suppressed diagnostics are filtered when reportSuppressedDiagnostics is false.
Please see this comment. https://github.com/dotnet/roslyn/pull/53045#discussion_r790530597
`GetCompilationWithAnalyzerDiagnostics` already contains the verification.

2022-02-08 04:53 UTC, cston commented on src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs
> +            // Verify suppressed diagnostics are filtered when reportSuppressedDiagnostics is false.
> `GetCompilationWithAnalyzerDiagnostics` already contains the verification.

Thanks. Please consider adding a comment here that it's handled in `GetCompilationWithAnalyzerDiagnostics`.

2022-02-08 16:01 UTC, cston approved these changes

2022-02-24 18:32 UTC, mavasani commented
@dotnet/roslyn-compiler for second review.

2022-03-15 21:37 UTC, 333fred approved these changes

2022-03-16 02:38 UTC, merged