Use a sentinel value in the lightbulb code to simplify logic.
dotnet/roslyn pull request #53131
Opened 2021-05-04 03:26 UTC by CyrusNajmabadi

2021-05-04 06:53 UTC, allisonchou approved these changes
Just some super small comment nits, feel free not to take them 😄

2021-05-04 06:53 UTC, allisonchou commented on src/Workspaces/Core/Portable/Workspace/Host/Status/NoOpWorkspaceStatusService.cs
> +            // by the default, we are always fully loaded
```suggestion
            // by default, we are always fully loaded
```

2021-05-04 06:53 UTC, allisonchou commented on src/Workspaces/Core/Portable/Workspace/Host/Status/NoOpWorkspaceStatusService.cs
> +            // by the default, we are always fully loaded
```suggestion
            // by default, we are always fully loaded
```

2021-05-04 14:27 UTC, sharwell requested changes
Export a default instance of `IWorkspaceStatusService` instead of using a singleton.

2021-05-04 14:31 UTC, sharwell commented
I believe we should take https://github.com/dotnet/roslyn/pull/49051 instead of this change.

2021-05-04 15:21 UTC, CyrusNajmabadi commented
> Edit: a default instance of WorkspaceStatusService is already available.

Right. But that only works if we have a workspace. When we don't, there's no sentinel that we can use. 

That said, we found change our logic to never store this service and instead always grab it from the workspace when we attach/detach from that.

2021-05-04 16:09 UTC, CyrusNajmabadi commented
@sharwell removed the NoOp service in favor of just on demand retrieval of the the status service.

2021-05-04 21:56 UTC, sharwell approved these changes

2021-05-05 04:08 UTC, sharwell approved these changes

2021-05-05 04:08 UTC, sharwell commented
/azp run

2021-05-05 05:16 UTC, merged