Fix the word 'hang'
dotnet/roslyn pull request #53501
Opened 2021-05-18 23:38 UTC by Cosifne

PoliCheck bug:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1323549/?triage=true

2021-05-18 23:39 UTC, jinujoseph approved these changes

2021-05-18 23:53 UTC, JoeRobich approved these changes

2021-05-19 00:31 UTC, sharwell requested changes

2021-05-19 00:31 UTC, sharwell commented on src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
> +                // Any feature that waits for LSP server activations to complete will stop responding because of the old incomplete server activation tasks.
Hang is explicitly allowed in this technical context. Replacement is acceptable with one of the following technical alternatives on condition that the correct alternative is known and used.

* **Deadlock** (e.g. lock inversion)
* **Livelock** (e.g. infinite loop)
* **UI delay** long enough that it is indistinguishable from one of the former

2021-05-19 05:58 UTC, sharwell commented on src/VisualStudio/IntegrationTest/TestUtilities/VisualStudioInstanceFactory.cs
> +                // Any feature that waits for LSP server activations to complete will stop responding because of the old incomplete server activation tasks.
For the scenario described here, 'deadlock' is an appropriate term. The internal issue is already resolved as Won't Fix, so it is at least as acceptable (if not more so) to just close this PR as won't fix.

2021-05-19 16:46 UTC, closed without merging