Support multi-caret when inserting doc comments
dotnet/roslyn pull request #54741
Opened 2021-07-10 08:46 UTC by Youssef1313

![gif](https://user-images.githubusercontent.com/31348972/125157556-00bc7380-e16c-11eb-9f3d-b8e43cf629af.gif)

2021-07-10 08:47 UTC, CyrusNajmabadi commented
I'm ok with this (esp. with how minimal the code is).  but would def want a test for this :)

2021-07-10 08:47 UTC, CyrusNajmabadi commented
Is thsi fixing some reported issue?

2021-07-10 08:50 UTC, Youssef1313 commented
> Is thsi fixing some reported issue?

Yeah I forgot to add it. Will link it from PR description: https://github.com/dotnet/roslyn/issues/54391

2021-07-10 09:04 UTC, Youssef1313 commented
Test infrastructure doesn't seem to be working with multi-caret. I'll look into how to fix that.

2022-01-16 13:13 UTC, Youssef1313 commented
@CyrusNajmabadi I was unable to write a test. Can you take a look so that we can get it merged? Thanks!

2022-01-16 13:13 UTC, Youssef1313 commented on src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs
> +
```suggestion
```

2022-01-23 15:48 UTC, Youssef1313 commented
@CyrusNajmabadi Can you take a look please?

2022-02-04 23:01 UTC, sharwell commented
@Youssef1313 should be possible to write an integration test for this in the new integration test project

2022-02-04 23:01 UTC, sharwell requested changes
An integration test should be easy in the new integration test project

2022-02-05 07:32 UTC, Youssef1313 commented
@sharwell Which project? Can you point me please? Thanks!

2022-02-07 04:40 UTC, sharwell commented
![image](https://user-images.githubusercontent.com/1408396/152725485-1d323419-dc95-472d-8ddd-2d6cf10a8abf.png)

2022-02-07 04:41 UTC, sharwell commented
The current tests have examples for how to do a bunch of different things. If you don't see a similar example for something you need, feel free to ask.

2022-02-07 07:35 UTC, Youssef1313 commented
@sharwell I couldn't find a test that does multi-caret. When I tried to do it I got `System.ArgumentException : Saw multiple occurrences of $$`

```csharp
        [IdeFact]
        [WorkItem(54391, "https://github.com/dotnet/roslyn/issues/54391")]
        public async Task TypingCharacter_MultiCaret()
        {
            var code =
@"
//$$
class C1 { }

//$$
class C2 { }

//$$
class C3 { }
";
            await SetUpEditorAsync(code, HangMitigatingCancellationToken);
            await TestServices.Input.SendAsync('/');
            var expected =
@"
/// <summary>
/// $$
/// </summary>
class C1 { }

/// <summary>
///
/// </summary>
class C2 { }

/// <summary>
///
/// </summary>
class C3 { }
";

            await TestServices.EditorVerifier.TextContainsAsync(expected, cancellationToken: HangMitigatingCancellationToken);
        }
```

2022-02-07 07:38 UTC, Youssef1313 commented
Also tried:

```csharp
//$$
class C1 { }

//[||]
class C2 { }

//[||]
class C3 { }
```

But fails with `System.Runtime.InteropServices.COMException : Error HRESULT E_FAIL has been returned from a call to a COM component.`

2022-02-07 11:34 UTC, davidwengier commented
@Youssef1313 I took the liberty of updating the test. The issues were:

* The test framework didn't support multi-caret, so I added some basic support
* You didn't have a constructor in your test class, so didn't get a solution and project automatically created, so when calling `SetupEditorAsync` the COM exception occurred, because there wasn't an editor to setup.
* You weren't asserting the caret position, so the test was expecting to see `$$` in the actual editor
* You missed a couple of bits of whitespace

All in all though, you did a great job (unsurprisingly 😁)

2022-02-07 11:44 UTC, Youssef1313 commented
@davidwengier Thanks a lot!!

2022-02-07 11:57 UTC, MartyIX commented
@Youssef1313 Do you have more up-to-date gif? Just curious. ;-)

2022-02-07 12:01 UTC, Youssef1313 commented
@MartyIX Oh looks like the software I used produced a bad GIF 😄 

Will build the branch and update it soon.

2022-02-07 22:33 UTC, sharwell approved these changes

2022-02-07 22:34 UTC, merged