Update PooledObjects.Package to target net46
dotnet/roslyn pull request #55352
Opened 2021-08-02 22:02 UTC by JoeRobich

Reported on teams:

> i just sync'ed to main and i'm getting this now:
```
Severity    Code    Description    Project    File    Line    Suppression State
Error    MSB3644    The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks    Microsoft.CodeAnalysis.PooledObjects.Package    C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets    1217 
```

The net45 targeting pack is no longer installable through the VS 2022 installer. This moves the project to build against net46 which is installed by default with VS2022.

2021-08-02 22:03 UTC, CyrusNajmabadi approved these changes

2021-08-02 23:33 UTC, sharwell requested changes
The targeting pack should not be necessary for this. The only requirement should be a reference to [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/). The change proposed in this pull request is a strong indication that a Visual Studio 2022 upgrade is going to unnecessarily break projects in the wild.

2021-08-02 23:40 UTC, JoeRobich commented
> The targeting pack should not be necessary for this. The only requirement should be a reference to Microsoft.NETFramework.ReferenceAssemblies. 

Thanks Sam. I keep forgetting that exists. Updated PR.

2021-08-03 00:46 UTC, JoeRobich commented
Passing Roslyn CI - https://dev.azure.com/dnceng/public/_build/results?buildId=1272321&view=results
Passing Roslyn Integration CI - https://dev.azure.com/dnceng/public/_build/results?buildId=1272322&view=results

2021-08-03 00:48 UTC, JoeRobich commented
@sharwell Let me know if this is the change you had in mind.

2021-08-03 04:08 UTC, sharwell commented
@JoeRobich The reference assemblies package appears to be automatically included, and the only reason it wasn't working is https://github.com/dotnet/roslyn/pull/55359.

2021-08-03 12:58 UTC, merged