Fix reversed output in interpolation concatenation
dotnet/roslyn pull request #55494
Opened 2021-08-07 13:41 UTC by Youssef1313

Fixes #55493
Fixes #55461

2021-08-07 14:32 UTC, 333fred requested changes
Don't use a reverse on the parts arrays, reverse the builder after populating.

2021-08-07 14:41 UTC, Youssef1313 commented
@333fred The builder is indeed reversed at the end of the method, but that wasn't enough. To reverse a builder, I'd have to create a  new builder for each `BoundInterpolatedString`, or loop backwards on `Parts` and use `Add` for each part (instead of `AddRange(Parts)`.

Alternatively, attempt to rewrite the code such that we don't need reversing at all (ie, walk from left to right - but I'm not sure how hard is that or if that's possible).

2021-08-07 14:43 UTC, 333fred commented
Left to right isn't feasible. If we need to add these in reverse order here as well, we should not use linq to do so.

2021-08-07 14:45 UTC, 333fred commented
I'm also concerned about flow analysis. Make sure we have a test like `$"{a = null}{a.ToString()}" + $""`

2021-08-07 15:26 UTC, 333fred commented on src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs
> +try
Needs to be nullable enabled to test the flow analysis.

2021-08-07 15:26 UTC, 333fred commented on src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs
> +using System.Linq;
Unused.

2021-08-07 16:19 UTC, 333fred approved these changes
@jcouv ptal.

2021-08-09 19:36 UTC, jcouv approved these changes
LGTM Thanks (iteration 4)

2021-08-10 07:16 UTC, jcouv commented
Looks like there is a legitimate failure: `InterpolatedStringsAddedUnderObjectAddition3` in the spanish CI branch because of localization of `"Object reference not set to an instance of an object."`. Consider just printing the exception type name.

2021-08-10 18:50 UTC, merged

2021-08-10 18:50 UTC, jcouv commented
Thanks @Youssef1313