Change Inheritance Margin Header style
dotnet/roslyn pull request #55533
Opened 2021-08-10 20:17 UTC by Cosifne

As discussed with the UX, make the inheritance margin's header look like the Control Q search page.
Light theme:
![image](https://user-images.githubusercontent.com/24360909/128928644-f3cc90b5-47c7-4a28-bd2c-4aa2d14d78d5.png)
![image](https://user-images.githubusercontent.com/24360909/128928663-fd7da084-49e9-4b9e-9948-8da0e7285c96.png)

Black theme:
![image](https://user-images.githubusercontent.com/24360909/128928170-fcd29b2b-3a43-4665-809b-ded11a22b641.png)
![image](https://user-images.githubusercontent.com/24360909/128928582-235d832b-2f67-4f84-9e73-a85e2f5f514a.png)

Blue theme:
 
![image](https://user-images.githubusercontent.com/24360909/128928753-9a9f553f-419a-42cb-8086-f5ea7af683d3.png)
![image](https://user-images.githubusercontent.com/24360909/128928772-d20df374-f92e-44fe-bab8-14f6113a941d.png)

2021-08-10 20:18 UTC, ryzngard approved these changes

2021-08-10 20:35 UTC, sharwell commented
Hmm. I really prefer the way we have it already.

2021-08-10 20:42 UTC, CyrusNajmabadi commented
Fwiw, this looks worse to me.  So we need to make this change?

2021-08-10 20:43 UTC, sharwell requested changes
Two negative reviews now suggest we should consider alternatives.

2021-08-10 21:50 UTC, Cosifne commented
Sounds like we should loop some UX folk in this thread.
@mikadumont 
Do you know who should be the best UX contact here?

2021-08-17 18:27 UTC, mikadumont commented
We had a UX review and need to follow the style guidelines for headers. They had an issue with having a background color.

2021-08-18 19:27 UTC, Cosifne commented
It feels like people still want the background color but the UX doesn't like it.
Should we discuss this issue with the UX again and
in the meanwhile, I feel we need to change the background color for the blue theme
![image](https://user-images.githubusercontent.com/24360909/129959918-d77ed608-0111-40f0-bc1b-807b961b5df8.png)
It looks a little bit strange.
@sharwell @CyrusNajmabadi  @mikadumont  Does this conclusion make sense to you?

2021-08-18 23:16 UTC, JoeRobich commented
I wonder if a horizontal separate between the header and items would make this change palatable.

2021-08-18 23:20 UTC, sharwell commented
I really like the style we have right now. It makes it very easy to see the information of interest, and clearly separates the headers from the individual menu items. The blue theme contrast issue is being addressed separately, so I'm not sure further action is necessary.

2021-08-19 05:18 UTC, CyrusNajmabadi commented
I agree with sam.  The current style looks very good.  It's clear and fits the theme in all the styles i've tried.  I don't actually know why we need to change anything here.  

Can UX clarify why they think a change is needed here?

2021-08-19 05:19 UTC, CyrusNajmabadi commented
> As discussed with the UX, make the inheritance margin's header look like the Control Q search page.

Note: while these are headers, they're not tabs.  So the idea of making inheritance margin match Control Q doesn't make much sense to me.

2021-09-23 21:53 UTC, Cosifne commented
Close this PR because this looks like not need so far

2021-09-23 21:53 UTC, closed without merging