Prevent exception if their is no else block.
dotnet/roslyn pull request #55656
Opened 2021-08-17 00:38 UTC by AdamSpeight2008

Previously would fail with `Null Reference Exception` , if the `ifBlock` didn't have and `elseBlock`
```vbnet
If condition Then
  Console.WriteLine("Statement")
End If
```

2021-08-17 02:14 UTC, ryzngard commented on src/Features/VisualBasic/Portable/InvertIf/VisualBasicInvertIfCodeRefactoringProvider.MultiLine.vb
> +        Return elseBlock IsNot Nothing AndAlso elseBlock.GetLeadingTrivia().Any(Function(trivia) trivia.IsKind(SyntaxKind.CommentTrivia))
```suggestion
            Return elseBlock IsNot Nothing AndAlso elseBlock.GetLeadingTrivia().Any(Function(trivia) trivia.IsKind(SyntaxKind.CommentTrivia))
```

2021-08-17 18:13 UTC, ryzngard approved these changes

2021-08-17 18:13 UTC, ryzngard requested changes
Can you add a test for this case?

2021-08-17 18:54 UTC, AdamSpeight2008 commented
> Can you add a test for this case?

I don't know where the unit tests are? For this area of the Roslyn repo.

2021-08-17 19:01 UTC, ryzngard commented
> > Can you add a test for this case?
> 
> I don't know where the unit tests are? For this area of the Roslyn repo.

It doesn't look like there are any :( We have csharp but no VB tests. https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs 

Filed #55677 to add tests

2021-08-17 19:01 UTC, ryzngard approved these changes

2021-08-17 19:06 UTC, AdamSpeight2008 commented
Example that triggera the exception in current version of code.
```vb,net
Imports System

Module Program
  Sub Main(args As String())
    Dim condition As Boolean = False
    If condition Then ' Trigger Code Action on this line.
      Console.WriteLine("Hello World!")
    End If
  End Sub
End Module

```

2021-08-17 19:14 UTC, CyrusNajmabadi commented
We shoudl still add tests here.  @AdamSpeight2008 if you'd like, we can do that though.  Please let us know.  @ryzngard can you help with that if Adam doesn't have time?

2021-08-17 19:17 UTC, ryzngard commented
@CyrusNajmabadi yea, I filed an issue and assigned to myself. We definitely need coverage here and I should be able to get tests going this afternoon.

2021-08-17 21:34 UTC, AdamSpeight2008 commented
@ryzngard If you can add the unit test for this one, I'll then help adding additional coverage and examples.

2021-08-28 00:25 UTC, AdamSpeight2008 commented
@ryzngard Add an unit test for this case.

2021-08-28 01:24 UTC, ryzngard commented
> @ryzngard Add an unit test for this case.

I'll add one this weekend

2021-08-30 00:47 UTC, ryzngard commented
Ah, I see you did :)

2021-08-30 00:48 UTC, merged