Revert "Re-enable BuildWithCommandLine test"
dotnet/roslyn pull request #57687
Opened 2021-11-10 23:36 UTC by allisonchou

It looks like BuildWithCommandLine still isn't working after being re-enabled in https://github.com/dotnet/roslyn/pull/57584.
We should disable it for the time being to prevent the test from blocking the pipeline.

2021-11-10 23:37 UTC, allisonchou commented
cc @sharwell cc @jasonmalinowski

2021-11-11 18:42 UTC, JoeRobich approved these changes

2021-11-11 18:54 UTC, sharwell requested changes
Before merging, requesting verification that we have at least one failure of this test in a branch which was not impacted by the shortened timeout (#57711).

2021-11-11 18:58 UTC, allisonchou commented
It looks like increasing the timeout will likely fix this issue as well. (https://github.com/dotnet/roslyn/pull/57711)
Closing this PR for now, will re-open if necessary.

2021-11-11 18:58 UTC, closed without merging