Skip flaky test WorkspaceClearedAfterReset
dotnet/roslyn pull request #57702
Opened 2021-11-11 05:31 UTC by allisonchou

This test is consistently flaky and is tracked by https://github.com/dotnet/roslyn/issues/57701.

2021-11-11 05:59 UTC, Cosifne approved these changes

2021-11-11 16:42 UTC, sharwell requested changes
I saw no evidence of flakiness in main, so can this be retargeted to main-vs-deps?

2021-11-11 17:52 UTC, allisonchou commented
@sharwell Can you give an example of how to use `ConditionalWpfFact`? Doesn't look like there are usages in the repo to base off from.

2021-11-11 18:03 UTC, jaredpar commented
>  Can you give an example of how to use ConditionalWpfFact? Doesn't look like there are usages in the repo to base off from.

It's use cases are exactly like `ConditionalFact`. The only difference is that when enabled it hooks into the WPF runner. So just base the usage you need of existing `ConditionalFact` in the code base.

2021-11-11 18:25 UTC, allisonchou commented
Thanks! Sam has diagnosed the root cause of the flaky test, so I'm going to close this PR and re-open another with the fix.

2021-11-11 18:25 UTC, closed without merging

2021-11-12 17:33 UTC, sharwell commented
Superseded by #57711