Don't offer to use patterns when they won't work
dotnet/roslyn pull request #60370
Opened 2022-03-24 21:00 UTC by davidwengier

Fixes https://github.com/dotnet/roslyn/issues/57199

2022-03-25 06:21 UTC, Youssef1313 commented on src/Analyzers/CSharp/Analyzers/UsePatternCombinators/AnalyzedPattern.cs
> +                // We are coming from a type pattern, which only binds to types, but converting to
I think "*only*" is not accurate. It can bind to expressions if no type is found.

2022-03-25 06:26 UTC, Youssef1313 reviewed
Is using `SpeculativeSemanticModel` better for this scenario? That way we'll be referring to the compiler back instead of trying to mimmic its logic.

I believe @CyrusNajmabadi has used speculation for the unnecessary cast feature, and it worked reallyy great.

2022-03-25 06:34 UTC, Youssef1313 commented on src/EditorFeatures/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs
> +        private class Goo
The most outer class is private. This is a compile error. Consider making public

2022-03-25 06:34 UTC, Youssef1313 commented on src/EditorFeatures/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs
> +                if [|(o is X || o is Y)|]
Consider testing:

```csharp
        public class Goo
        {
            private class X { }
            private class Y { }
            private void M(object o)
            {
                var X = 1;
                var Y = 2;
                if (o is global::Goo.X || o is Y)
                {
                }
            }
        }
```

2022-03-25 08:12 UTC, Youssef1313 reviewed
I have another idea. Why not generate keep the analyzer the same, ie, report a diagnostic, and fix the CodeFixProvider to generate a valid code. It's always possible to refer to the type using a fully qualified name with `global::` I think?

We can always produce the node with `global::` + fully qualified name, then add `WithAdditionalAnnotations(Simplifier.Annotation);` which should simplify the name if possible.

2022-03-25 08:28 UTC, davidwengier commented
Might just be me, but I wouldn't like a fix that uses `global::`, so I wouldn't want anything offered unless we can be sure it would be simplified out.

I'm not sure this warrants the complexity.

2022-03-25 08:57 UTC, Youssef1313 reviewed
Does it work for the following?

```csharp
public class Goo
{
    private struct X { }
    private struct Y { }
    private void M(object o)
    {
        const int X = 1;
        const int Y = 2;
        if (o is X? || o is Y?) // error if converted to o is X? or Y?
        {
        }
    }
}
```

I think there can be other edge cases we cannot see easily (the above may not be included, it could be currently working). That's why I think referring back to SpeculativeSemanticModel is the most accurate fix.

2022-03-25 09:37 UTC, davidwengier commented
> That's why I think referring back to SpeculativeSemanticModel is the most accurate fix.

I did try using that, but it didn't work. I've never used it before though so could very well be something I did wrong.

2022-03-25 10:25 UTC, Youssef1313 commented
@davidwengier This has worked for me:

https://github.com/dotnet/roslyn/commit/3a708f6184f4a8a679dd772ceafd9155820a38e4 (built on top of your branch)

The added test was failing before 3a708f6184f4a8a679dd772ceafd9155820a38e4.

2022-03-25 10:31 UTC, davidwengier commented
Thank you for the education @Youssef1313, I was [way off](https://github.com/dotnet/roslyn/pull/60370/commits/1da729c7e712edfd2242dfd680c133ef7bc72287#diff-b7c98c8025dfc92ec777b6fe9cca78888430bb776ad90cb56688dadaa56c8fb1R28)!!

2022-03-28 17:04 UTC, mychang666 requested changes
`

2022-03-28 20:25 UTC, davidwengier commented
@mychang666 Did you accidentally submit your comment early?

2022-03-28 20:25 UTC, davidwengier commented
Ping @dotnet/roslyn-ide and/or @CyrusNajmabadi for review

2022-03-28 22:13 UTC, CyrusNajmabadi commented on src/Analyzers/CSharp/Analyzers/UsePatternCombinators/AnalyzedPattern.cs
> +                }
cute!

2022-03-28 22:13 UTC, CyrusNajmabadi approved these changes

2022-03-28 22:40 UTC, davidwengier commented
Thanks for your help @Youssef1313

2022-03-28 22:41 UTC, merged