Fix the KeybindingResetDetector
dotnet/roslyn pull request #60494
Opened 2022-03-31 00:31 UTC by jasonmalinowski

We switched VisualStudioInfoBar to no longer be a MEF service in 347cd02a80446b47eb93d1effc6d675810457bc2, but this was still importing it. It's now a helper type, so create it instead.

2022-03-31 00:35 UTC, davidwengier approved these changes

2022-03-31 00:35 UTC, jmarolf approved these changes

2022-03-31 00:40 UTC, CyrusNajmabadi commented on src/VisualStudio/Core/Def/KeybindingReset/KeybindingResetDetector.cs
> -            VisualStudioInfoBar infoBarService,
i don't get it.  shouldn't this have broken mef?  how was this type getting instantiated?  and how did this not break anything else importing KeybindingResetDetector?

2022-03-31 00:40 UTC, CyrusNajmabadi requested changes
Something doesn't make sense to me here.

2022-03-31 00:41 UTC, jasonmalinowski commented
@CyrusNajmabadi: It throws exceptions here:

https://github.com/dotnet/roslyn/blob/91bd6e559166e4550e4e975d827ef301b4d62d1e/src/VisualStudio/Core/Def/RoslynPackage.cs#L260-L261

Which is a fire-and-forget path.

2022-03-31 01:17 UTC, CyrusNajmabadi commented
bleaghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.

2022-04-05 19:39 UTC, jasonmalinowski commented
@CyrusNajmabadi Updated to report non-fatal telemetry if that throws.

2022-04-11 23:49 UTC, jasonmalinowski commented
Some testing makes us think this feature is more generally broken; until we understand why we'll merge this for 17.3 to avoid the MEF composition issue, and we'll need to investigate further.

2022-04-13 20:46 UTC, merged