Shadow Copy all analyzer dependencies
dotnet/roslyn pull request #61974
Opened 2022-06-16 22:52 UTC by jmarolf

Previously we just copied the assembly and its resources. Most analyzers have dependencies that live next to the assembly that are also necessary

fixes https://developercommunity.visualstudio.com/t/Several-CS8032-warnings-appears-in-Error/10043881

2022-06-16 22:53 UTC, jmarolf commented
@RikkiGibson I want to ensure that we are doing the same thing in the Shadow Copy loader as the compiler is doing.

2022-06-17 00:32 UTC, sharwell requested changes
❗ We intentionally do not copy files that exist alongside the analyzer assembly. We only copy assemblies that are explicitly passed to the compiler via an `<Analyzer>` item, as these are the only items tracked by MSBuild and the project system for up-to-date checks.

2022-06-17 03:54 UTC, jmarolf commented
> ❗ We intentionally do not copy files that exist alongside the analyzer assembly. We only copy assemblies that are explicitly passed to the compiler via an `<Analyzer>` item, as these are the only items tracked by MSBuild and the project system for up-to-date checks.

I agree that this PR should be updated to not copy _all_ dlls but just the ones that are given to us as analyzer references.

However, the current implementation for the shadow-copier is not correct in terms of how we ourselves ship analyzers.

Consider [microsoft.codeanalysis.analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers). This package ships with the following package structure:

```
<Package Root>
└───analyzers
    └───dotnet
        ├───cs
        │       Microsoft.CodeAnalysis.Analyzers.dll
        │       Microsoft.CodeAnalysis.CSharp.Analyzers.dll
        │
        └───vb
                Microsoft.CodeAnalysis.Analyzers.dll
                Microsoft.CodeAnalysis.VisualBasic.Analyzers.dll
```

The current implementation will shadow-copy `Microsoft.CodeAnalysis.Analyzers.dll` and `Microsoft.CodeAnalysis.CSharp.Analyzers.dll` to completely separate directories. The Compiler analyzer loader handles this package just fine, but our shadow-copy implementation will fail to load this analyzer. We should unify our approaches so we do not have disjoint sets of analyzer packages that we support based on which loader is being used.

2022-06-17 03:55 UTC, jmarolf commented
@RikkiGibson what is the compilers analyzer load strategy on .NET Framework?

2022-06-17 17:22 UTC, mavasani commented
Also tagging @tmat @genlu who have dealt with analyzer assembly loading in the past

2022-06-17 18:02 UTC, sharwell commented
> The current implementation will shadow-copy Microsoft.CodeAnalysis.Analyzers.dll and Microsoft.CodeAnalysis.CSharp.Analyzers.dll to completely separate directories. 

There are two equally-acceptable solutions:

* Keep track of where each assembly is copied, and use an assembly resolve/load handler to locate assemblies that were originally "next to" the requesting assembly
* Update the shadow copy implementation to create a unique directory for each source directory instead of a unique directory for each source assembly

2022-06-17 19:45 UTC, genlu commented
> Update the shadow copy implementation to create a unique directory for each source directory instead of a unique directory for each source assembly

I really like this approach. 👍

2022-07-06 16:32 UTC, jmarolf commented
@dotnet/compat I am seeing this error in the build:

```
##[error]eng\targets\Bootstrap.targets(4,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Analyzer inconsistency building D:\a\_work\1\s\artifacts\obj\Microsoft.CodeAnalysis\Release\netstandard2.0\Microsoft.CodeAnalysis.dll
```

How do I investigate this?

2022-07-07 05:01 UTC, jaredpar commented
@jmarolf 

When the build correctness leg fails it uploads the VBCSCompiler server logs as an artifact and that usually has pretty detailed information on why a failure happened. If it doesn't then generally it's considered a bug and a place for us to add more information 😄 . 

The file name is Build.Server.Log. In this particular case I see the following error: 

```txt
ID=VBCSCompiler TID=12: Error Error: 'IOException' 'The file 'T:\VBCSCompiler\AnalyzerAssemblyLoader\07bc30fa669c473389850bfb58a17d34\2\Microsoft.CodeAnalysis.Analyzers.dll' already exists.' occurred during 'Analyzer Consistency Check'
Stack trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.CodeAnalysis.ShadowCopyAnalyzerAssemblyLoader.CopyFile(String originalPath, String shadowCopyPath) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs:line 173
   at Microsoft.CodeAnalysis.ShadowCopyAnalyzerAssemblyLoader.CopyFileAndDependencies(FileInfo existingFile, String assemblyDirectory, IEnumerable`1 declaredDependentAssemblies) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs:line 129
   at Microsoft.CodeAnalysis.ShadowCopyAnalyzerAssemblyLoader.GetPathToLoad(String fullPath) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs:line 109
   at Microsoft.CodeAnalysis.DefaultAnalyzerAssemblyLoader.LoadFromPathUncheckedImpl(String fullPath) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:line 57
   at Microsoft.CodeAnalysis.AnalyzerAssemblyLoader.LoadFromPathUnchecked(String fullPath) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:line 94
   at Microsoft.CodeAnalysis.AnalyzerAssemblyLoader.LoadFromPath(String fullPath) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:line 68
   at Microsoft.CodeAnalysis.CompilerServer.AnalyzerConsistencyChecker.CheckCore(String baseDirectory, IEnumerable`1 analyzerReferences, IAnalyzerAssemblyLoader loader, ICompilerServerLogger logger, List`1& errorMessages) in /_/src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs:line 89
   at Microsoft.CodeAnalysis.CompilerServer.AnalyzerConsistencyChecker.Check(String baseDirectory, IEnumerable`1 analyzerReferences, IAnalyzerAssemblyLoader loader, ICompilerServerLogger logger, List`1& errorMessages) in /_/src/Compilers/Server/VBCSCompiler/AnalyzerConsistencyChecker.cs:line 37
```

This is happening when building inside `D:\a\_work\1\s\src\Compilers\Core\Portable` so it's going to be building Microsoft.CodeAnalysis.csproj. Looking at the binlog, also in the artifacts, I see the following values passed as analyzers 

<img width="767" alt="image" src="https://user-images.githubusercontent.com/146967/177694903-3f758e92-b6e9-4e56-83d8-2f0ad154b246.png">

I don't see Microsoft.CodeAnalysis.Analyzers.dll being passed twice. So my suspicion is something in this PR is already populating the shadow directory with that file and it's getting re-used between builds.

2023-03-02 22:30 UTC, closed without merging