Don't load parts early from MEF that aren't needed
dotnet/roslyn pull request #62090
Opened 2022-06-22 23:24 UTC by jasonmalinowski

When our package loads, we register our library objects which is what drives class view and object browser. The constructor for this proactively loads a few services which are then only used if you invoked go to definition or find references through the object browser. It's a tiny cost (25ms) in one trace but each little bit counts when trying to make load times better.

2022-06-22 23:58 UTC, JoeRobich approved these changes

2022-06-23 14:18 UTC, sharwell requested changes

2022-06-23 14:18 UTC, sharwell commented on src/VisualStudio/Core/Def/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs
> +                                _ = FindReferencesAsync(streamingPresenter, symbolListItem, project);
❗ The life asynchronous operations must be captured at the call site, either by awaiting or by using a listener. We haven't figured out a way to analyze this cleanly, so it has to be seen in a review.

2022-06-23 14:20 UTC, sharwell commented on src/VisualStudio/Core/Def/Library/ObjectBrowser/ObjectList.cs
> +                using var token = asynchronousOperationListener.BeginAsyncOperation(nameof(GoToSourceAsync));
📝 There is no asynchronous work started in this method which is not already captured by this method. It is unlikely that this token is needed here; if it's used at all it should be relocated to whichever caller started an operation that wasn't awaited.

2022-06-23 14:24 UTC, sharwell commented on src/VisualStudio/Core/Def/Library/ObjectBrowser/ObjectList.cs
> +                using var token = asynchronousOperationListener.BeginAsyncOperation(nameof(GoToSourceAsync));
Yep, the caller is incorrect:
https://github.com/dotnet/roslyn/blob/69bdfb29ce4d027c5f5bf70f50be9bebcb5df1aa/src/VisualStudio/Core/Def/Library/AbstractObjectList.cs#L317-L318

2022-06-23 14:28 UTC, sharwell commented on src/VisualStudio/Core/Def/Library/ObjectBrowser/ObjectList.cs
> +                var asynchronousOperationListener = _manager.ComponentModel.GetService<IAsynchronousOperationListenerProvider>().GetListener(FeatureAttribute.LibraryManager);
📝 There are multiple locations in this feature that are incorrectly handling asynchronous operations. We shouldn't rely on each location to obtain the correct specific listener on demand.

2022-06-24 21:50 UTC, jasonmalinowski commented
@sharwell: updated some of the places to avoid the fire-and-forgets that this PR was touching. I wouldn't be surprised if there's plenty more badness in this area of the codebase, but I don't want to hold up the original intent of this PR trying to fix unrelated things.

2022-06-27 15:36 UTC, sharwell commented on src/VisualStudio/Core/Def/Library/AbstractObjectList.cs
> +            var asynchronousOperationListener = LibraryManager.ComponentModel.GetService<IAsynchronousOperationListenerProvider>().GetListener(FeatureAttribute.LibraryManager);
💡 Can we make this a property of `LibraryManager`?

2022-06-27 15:38 UTC, sharwell approved these changes
Would like to see the listener refactored for easy re-use in the component, but now looks good.

2022-06-27 22:06 UTC, merged