Clarify error message when attempting to ref a property
dotnet/roslyn pull request #64764
Opened 2022-10-16 17:37 UTC by ArcadeMode

Proposes a fix for #60807

2022-10-17 09:30 UTC, jjonescz requested changes

2022-10-17 09:30 UTC, jjonescz commented on src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
> +//defenitions
```suggestion
//definitions
```

2022-10-17 14:42 UTC, ArcadeMode commented on src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs
> +//defenitions
Fixed 😊

2022-10-17 16:10 UTC, cston approved these changes

2022-10-18 07:40 UTC, jjonescz approved these changes

2022-10-18 15:03 UTC, merged

2022-10-18 15:04 UTC, cston commented
@ArcadeMode, thanks for the contribution.

2022-10-18 15:06 UTC, ArcadeMode commented
It was a small one but hopefully more substantial ones to come 😁