Remove "System.Threading.Channels" from vsix
dotnet/roslyn pull request #65028
Opened 2022-10-26 22:03 UTC by genlu

Blocked on the merge of https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/432121

2022-10-26 23:59 UTC, dibarbet approved these changes

2022-10-27 23:31 UTC, jasonmalinowski requested changes
This also needs to delete https://github.com/dotnet/roslyn/blob/bc641a6e58a5c15ac6b8052243c2b0dd97e65e1e/src/VisualStudio/Setup/Roslyn.VisualStudio.Setup.csproj#L331.

2022-10-28 00:23 UTC, genlu commented
I think this needs this change to work, which in turn requires this PR to avoid RPS regression
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/432121?_a=files&path=/src/SetupPackages/DeployableDotNetDependencies/DeployableDotNetDependencies.csproj

2022-10-28 16:48 UTC, jasonmalinowski approved these changes

2022-11-04 23:07 UTC, genlu commented
I have verified the change here:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/434001

2022-11-04 23:07 UTC, merged