Stop referencing packages that became inbox on modern .NET.
dotnet/roslyn pull request #65810
Opened 2022-12-06 17:24 UTC by teo-tsirpanis

See #65088.

@jmarolf, @jaredpar, @RikkiGibson

2022-12-07 11:35 UTC, teo-tsirpanis commented
CI is green.

2022-12-07 11:37 UTC, jjonescz commented on src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
> +<?xml version="1.0" encoding="utf-8"?>
File encoding changed?

2022-12-07 17:07 UTC, jaredpar requested changes

2022-12-07 17:07 UTC, jaredpar commented on src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
> +  </ItemGroup>
Please use `PackageReference ... Condition=` vs creating a new `ItemGroup`

2022-12-07 21:18 UTC, teo-tsirpanis commented on src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
> +<?xml version="1.0" encoding="utf-8"?>
The BOM was removed, brought it back.

2022-12-07 21:18 UTC, teo-tsirpanis commented on src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj
> +  </ItemGroup>
Done.

2022-12-08 04:02 UTC, jmarolf approved these changes
I sign off on the IDE changes

2022-12-12 03:58 UTC, jaredpar approved these changes

2023-01-03 17:32 UTC, teo-tsirpanis commented
Conflicts were resolved. Can it be merged?

2023-01-03 18:40 UTC, 333fred approved these changes

2023-01-03 19:02 UTC, merged