Remove usage of Workspace.Options from AutomationObject
dotnet/roslyn pull request #66211
Opened 2023-01-03 23:33 UTC by tmat

2023-01-03 23:39 UTC, Cosifne approved these changes

2023-01-04 00:17 UTC, 333fred approved these changes

2023-01-04 03:54 UTC, Cosifne requested changes
Temp hold this change because 17.6 branch is not needed, will need to retarget to main once change flows back to main

2023-01-04 20:04 UTC, Cosifne approved these changes

2023-01-04 20:11 UTC, tmat commented
/azp run

2023-01-05 01:56 UTC, merged