Provide access to F# integration tests
dotnet/roslyn pull request #66926
Opened 2023-02-16 19:17 UTC by psfinaki

We are ramping integration testing for F# and need internal access to some APIs, similar to how TypeScript or Razor have them.

The desired test in question is [here](https://github.com/dotnet/fsharp/pull/14764/files#diff-cb15dc9adef6f54d7312918096dbb1da9291da38a3b82d23ae12a1e22ef4095b). This currently fails [here](https://github.com/dotnet/fsharp/pull/14764/files#diff-c299ff93d2440ee88797821ae6c712f40b698914c9bf704baef2b4f5ff4868f4) when trying to access workspaces stuff:
![image](https://user-images.githubusercontent.com/5451366/219464980-a1baf72a-966a-4499-921c-84308d67236b.png)

We are really just trying to do what Roslyn repo does itself for C# [here](https://github.com/dotnet/roslyn/blob/af816d93f022d3f6d76284ea87ebc3fa98cf4705/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpNavigateTo.cs).

2023-02-17 04:11 UTC, Cosifne commented
I think the general strategy to share code is moving things to the external access pattern instead of directly using IVT. 
Is that difficult to be done?

2023-02-17 04:27 UTC, davidwengier commented
> similar to how TypeScript or Razor have them

We (Razor) don't have IVT in this manner, but use an external access layer as @Cosifne mentioned, though its worth noting we don't actually use that for our integration tests. So for example for Go To Definition, rather than trying to reach into the internals of Roslyn to wait for an async operation to finish, we just [wait for the active window](https://github.com/dotnet/razor/blob/main/src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs#L40) to be the one we expect. That helper method [just polls](https://github.com/dotnet/razor/blob/main/src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Text.cs#L122).

2023-02-17 20:27 UTC, sharwell requested changes

2023-02-17 20:27 UTC, sharwell commented on src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj
> +    <InternalsVisibleTo Include="FSharp.Editor.IntegrationTests" Key="$(FSharpKey)" />
❗ This must run through the external access layer. You can create a new project for F# integration tests, or you can reuse the existing F# external access project.

2023-02-17 20:27 UTC, sharwell commented on src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj
> +    <InternalsVisibleTo Include="FSharp.Editor.IntegrationTests" Key="$(FSharpKey)" />
❗ This must run through the external access layer. You can create a new project for F# integration tests, or you can reuse the existing F# external access project.

2023-02-17 20:27 UTC, sharwell commented on src/Workspaces/Core/Portable/Microsoft.CodeAnalysis.Workspaces.csproj
> +    <InternalsVisibleTo Include="FSharp.Editor.IntegrationTests" Key="$(FSharpKey)" />
❗ This must run through the external access layer. You can create a new project for F# integration tests, or you can reuse the existing F# external access project.

2023-02-17 20:29 UTC, sharwell commented
> For example, when testing Go To Definition rather than trying to reach into the internals of Roslyn to wait for an async operation to finish, we just [wait for the active window](https://github.com/dotnet/razor/blob/main/src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs#L40) to be the one we expect. That helper method [just polls](https://github.com/dotnet/razor/blob/main/src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Text.cs#L122). We don't currently have any NavigateTo tests (but we probably should!) but on the face of it, I see no reason the test you linked to couldn't be written the same way as our GTD test.

These strategies have totally different performance characteristics. When you wait for Roslyn asynchronous operations to complete, it immediately forces all delayed operations run to completion. See [`IExpeditableDelaySource`](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/TestHooks/IExpeditableDelaySource.cs).

2023-02-17 22:01 UTC, davidwengier commented
> somewhere between a code smell and an outright design bug

I would make the same statement about the fact that any of the Razor integration tests need to exist in the first place. When it comes to them, I'm of the opinion that if it's crazy and it works, then it's not crazy 😄

2023-02-20 15:59 UTC, psfinaki commented
Hah okay actually looks like we already have all the dependendies we are interested in, it's just that the integration tests project is new and doesn't have access to the external access layer yet - so fixing just this.

2023-02-20 15:59 UTC, psfinaki commented
So things makes sense now. @sharwell @Cosifne this should be sufficient for now.

2023-02-20 17:00 UTC, psfinaki commented
/azp run

2023-02-22 11:59 UTC, 0101 approved these changes

2023-02-22 12:17 UTC, psfinaki commented
/azp run

2023-02-22 15:46 UTC, sharwell approved these changes
This is now fine, but we should squash-merge this to avoid churn.

2023-02-22 15:46 UTC, merged