Add `<SourceGenerator>` MSBuild item type
dotnet/roslyn pull request #66974
Opened 2023-02-21 11:35 UTC by jjonescz

Instead of writing:

```csproj
<ItemGroup>
  <ProjectReference Include=".\MySourceGenerator1.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  <ProjectReference Include=".\MySourceGenerator2.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
</ItemGroup>
```

Allows one to write:

```csproj
<ItemGroup>
  <SourceGenerator Include=".\MySourceGenerator1.csproj" />
  <SourceGenerator Include=".\MySourceGenerator2.csproj" />
</ItemGroup>
```

Automatically adding all the properties, plus `AdditionalProperties="IsRidAgnostic=true"` (fixes #60744) and maybe more in the future.

2023-02-21 18:33 UTC, sharwell requested changes
I would prefer `AnalyzerProjectReference`, since this feature as defined also works for analyzers, and `OutputItemType="Analyzer"` is a better fit for the rename.

2023-02-21 19:30 UTC, 333fred commented
@jmarolf has been working on an MSBuild SDK for roslyn analyzers/generators, I'm not sure how this would interact.

2023-02-21 19:32 UTC, sharwell commented on src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets
> +      <ProjectReference Include="@(SourceGeneratorProjectReference)" OutputItemType="Analyzer" ReferenceOutputAssembly="false" AdditionalProperties="%(SourceGeneratorProjectReference.AdditionalProper
`ReferenceOutputAssembly` should still be a supported property. You'll need to use an item definition group to default this value to `false`.

```suggestion
      <ProjectReference Include="@(SourceGeneratorProjectReference)" OutputItemType="Analyzer" ReferenceOutputAssembly="%(ReferenceOutputAssembly)" AdditionalProperties="%(SourceGeneratorProjectReference.AdditionalProperties);IsRidAgnostic=true" />
```

2023-02-21 20:30 UTC, jasonmalinowski commented
I'd be a bit hesitant to for this generally, if only because we officially don't really "support" doing this at all. There's known limitations we don't currently have a plan to work around, specifically around reloading. I get we wrote this in the documentation, but if this is taken as more official support that might be bad.

2023-02-22 03:38 UTC, jaredpar commented
> I get we wrote this in the documentation, but if this is taken as more official support that might be bad.

I'm also a bit worried about making this more official. There are lots of odd details in MSBuild that are hard to get right. 

Could we offer this up as a sample for others to use in the meantime? I'd prefer a more official feature support in the msbuild / sdk layer for something like this.

2023-02-22 08:50 UTC, closed without merging