Multitarget O# external access projects to fix issues accessing prope…
dotnet/roslyn pull request #67163
Opened 2023-03-02 22:30 UTC by dibarbet

…rties on records

The last PR - https://github.com/dotnet/roslyn/pull/67106 was slightly incorrect - it fixed the build, but caused a bunch of test failures trying to call methods on records

```
System.MissingMethodException : Method not found: 'Void Microsoft.CodeAnalysis.Completion.CompletionOptions.set_ShowItemsFromUnimportedNamespaces(System.Nullable`1<Boolean>)'.[xUnit.net 00:00:19.95]       Stack Trace:[xUnit.net 00:00:19.95]            at Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.Completion.OmniSharpCompletionOptions.ToCompletionOptions()[xUnit.net 00:00:19.95]            at Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.Completion.OmniSharpCompletionService.GetCompletionsAsync(CompletionService completionService, Document document, Int32 caretPosition, CompletionTrigger trigger, ImmutableHashSet`1 roles, OmniSharpCompletionOptions options, CancellationToken cancellationToken)[xUnit.net 00:00:19.95]         /home/runner/work/omnisharp-roslyn/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs(95,0): at OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService.Handle(CompletionRequest request, Boolean forceExpandedCompletionIndexCreation)[xUnit.net 00:00:19.95]         /home/runner/work/omnisharp-roslyn/omnisharp-roslyn/tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs(2281,0): at OmniSharp.Roslyn.CSharp.Tests.CompletionFacts.FindCompletionsAsync(String filename, String source, OmniSharpTestHost testHost, Nullable`1 triggerChar, TestFile[] additionalFiles, Boolean forceExpandedCompletionIndexCreation)[xUnit.net 00:00:19.95]         /home/runner/work/omnisharp-roslyn/omnisharp-roslyn/tests/OmniSharp.Roslyn.CSharp.Tests/CompletionFacts.cs(301,0): at OmniSharp.Roslyn.CSharp.Tests.CompletionFacts.ImportCompletion_OnLine0(String filename, Boolean useAsyncCompletion)[xUnit.net 00:00:19.95]         --- End of stack trace from previous location ---
```

The root cause of that failure appeared to be a mismatch in the method signatures caused by the workspace version of IsExternalInit
```
.method public hidebysig specialname         instance void modreq([System.Runtime]System.Runtime.CompilerServices.IsExternalInit) set_ShowItemsFromUnimportedNamespaces (            valuetype [System.Runtime]System.Nullable`1<bool> 'value'        ) cil managed
```
vs the caller
```
IL_0016: callvirt instance void modreq([Microsoft.CodeAnalysis.Workspaces]System.Runtime.CompilerServices.IsExternalInit) [Microsoft.CodeAnalysis.Features]Microsoft.CodeAnalysis.Completion.CompletionOptions::set_ShowItemsFromUnimportedNamespaces(valuetype [netstandard]System.Nullable`1<bool>)
```

Switching over to appropriately multi-target the external access project appears to have fixed the issue in build and in the tests (so far).

2023-03-02 22:51 UTC, tmat approved these changes

2023-03-02 23:53 UTC, 333fred approved these changes

2023-03-03 18:47 UTC, sharwell commented
Are you interested in the other option here? All we need to do is add a `TypeForwardedTo` to **IsExternalInit.cs** so that it's part of the API surface in both binaries.

2023-03-03 18:48 UTC, sharwell requested changes
Need to answer the question before proceeding

2023-03-03 18:49 UTC, sharwell commented
I'll send a PR for a concrete example here

2023-03-03 18:57 UTC, sharwell commented
Submitted https://github.com/dotnet/roslyn/pull/67171

2023-03-03 19:05 UTC, dibarbet commented
@sharwell I'm not necessarily opposed to another fix, but O# multi-targets netframework and .netcore already, so multi-targeting the external access project doesn't seem inappropriate to me.

I can try out your change, but I don't think I'll be able to get to it until late this afternoon / Monday.

2023-03-03 19:19 UTC, dibarbet commented
Going ahead with this change since O# multi-targets and I already tested this one (and CI already finished).

2023-03-03 19:19 UTC, merged