Localize the output of run tests
dotnet/roslyn pull request #69121
Opened 2023-07-20 01:18 UTC by dibarbet

2023-07-20 15:09 UTC, sharwell requested changes

2023-07-20 15:09 UTC, sharwell commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.Designer.cs
> +namespace Microsoft.CodeAnalysis.LanguageServer {
This file should not be generated. Designer files are source generated by Arcade as part of the build.

2023-07-20 15:10 UTC, sharwell commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
> +  <data name="Found_0_tests in_1" xml:space="preserve">
```suggestion
  <data name="Found_0_tests_in_1" xml:space="preserve">
```

2023-07-20 15:15 UTC, sharwell commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj
> +
```suggestion
    <ItemGroup>
      <EmbeddedResource Update="LanguageServerResources.resx" GenerateSource=true" />
    </ItemGroup>

```

2023-07-20 15:16 UTC, sharwell commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
> +    <value>Strack Trace</value>
```suggestion
    <value>Stack Trace</value>
```

2023-07-20 15:17 UTC, sharwell commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServerResources.resx
> +  <data name="Summary_count" xml:space="preserve">
```suggestion
  <data name="Failed_0_Passed_1_Skipped_2_Total_3_Duration_4" xml:space="preserve">
```

2023-07-20 18:43 UTC, dibarbet commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Testing/TestDiscoverer.cs
> +        progress.Report(partialResult with { Message = string.Format(LanguageServerResources.Found_0_tests_in_1, matchedTests.Length, elapsed.ToString("g")) });
Updated - now it outputs strings like
![image](https://github.com/dotnet/roslyn/assets/5749229/ef6dd9b2-1979-4712-a251-9f707a649f5b)

![image](https://github.com/dotnet/roslyn/assets/5749229/e751811b-da3f-4241-a88e-0fd2e9030541)

![image](https://github.com/dotnet/roslyn/assets/5749229/cc164711-d6be-47e9-b670-f46aa8b9e1d5)

2023-07-21 13:57 UTC, sharwell commented on src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Testing/RunTestsHandler.cs
> +        if (t.Milliseconds > 0 && t.TotalSeconds < 1)
`0ms` is acceptable for time span 0.

```suggestion
        if (t.TotalSeconds < 1)
```

2023-07-21 19:17 UTC, merged