Enable bootstrapped builds in VS test insertion YAML
dotnet/roslyn pull request #69130
Opened 2023-07-20 16:00 UTC by jcouv

In order to get speedometer results on an experimental [compiler codegen change](https://github.com/dotnet/roslyn/pull/67487), we need to temporarily enable bootstrapping.

2023-07-21 22:14 UTC, 333fred requested changes
Talked with Julien offline about this, and I think I'm going to need a complete explanation of why this needs to be in a separate PR that will slow down all roslyn CI for several days.

2023-07-21 22:16 UTC, jcouv commented
Sounds like we'll have to wait til @jaredpar is back, as I'm not able to provide sufficient details.

2023-07-31 16:51 UTC, 333fred commented
I also am still unsure why this needs to be checked in. Why does the compiler itself need to be built with the flag

2023-07-31 16:56 UTC, jcouv commented
> Why does the compiler itself need to be built with the flag?

We want a speedometer result of VS using roslyn bits using the new codegen. 
Bootstrapping is what will cause the roslyn bits to use the new codegen. Without bootstrapping, the roslyn bits would still use the old async codegen.

2023-07-31 17:01 UTC, 333fred approved these changes
> We want a speedometer result of VS using roslyn bits using the new codegen.
> Bootstrapping is what will cause the roslyn bits to use the new codegen. Without bootstrapping, the roslyn bits would still use the old async codegen.

Thanks. This, and that the file was not standard ci, were the pieces that I was missing.

2023-07-31 17:06 UTC, jcouv commented
@jaredpar for review. Thanks

2023-07-31 17:23 UTC, dibarbet commented
> > The file is named azure-pipelines-pr-validation.yml. If it's not actually for PR validation, maybe the file needs to be renamed.
> 
> I agree the name is confusing and I wish there we had a better one. I'm fine with renaming if @dibarbet agrees.

I'm fine with renaming, but the pipeline is specifically for validating PRs (against VS).  Maybe something like `azure-pipelines-test-insertion` or something?  I'll trust you all to come up with something good :)

2023-07-31 19:23 UTC, jcouv commented
I'm not planning to rename in this PR (not the intent, I'm just trying to unblock validation of a codegen change), that can be a follow-up.
@jaredpar for a second look. Thanks

2023-07-31 20:37 UTC, jaredpar commented
Yeah I don't want to change the name here. Just saying it's fine for another PR.

2023-07-31 20:38 UTC, jaredpar approved these changes

2023-08-01 06:48 UTC, merged