Exclude LSP projects from source build
dotnet/roslyn pull request #69244
Opened 2023-07-26 18:47 UTC by beccamc

Exclude LSP based projects from the source build to make sure that licensing for source build is correct. 

I'm updated the projects in LanguageServer. Let me know if there are other places I should look as well!

2023-07-26 19:06 UTC, tmat commented
@dibarbet Yes, test projects are automatically excluded

2023-07-26 19:08 UTC, tmat requested changes
Seems like they should already be excluded:
https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Directory.Build.props#L4

Does this line have no effect for some reason?

2023-08-01 19:50 UTC, beccamc commented
@tmat Is correct, the LanguageServer/Directory.Build.props seem to be working to exclude the Microsoft.CodeAnalysis.LanguageServer projects. I will revert the LanguageServer.csproj files. Jared helped me, and these are the projects being included in the sourcebuild:

![image](https://github.com/dotnet/roslyn/assets/9122518/277315d5-3430-45f1-a20d-20076fb7060b)

I took a look through them, and the following 5 have references to some VS language service (e.g. Microsoft.VisualStudio.LanguageServices). I am assuming anything with a Microsoft.VisualStudio.X reference is a problem. **Is that correct?** Any thoughts on if we can exclude the following 5 projects?

```
Microsoft.CodeAnalysis.Workspaces.csproj
Microsoft.CodeAnalysis.CSharp.Workspaces.csproj 
Microsoft.CodeAnalysis.CSharp.Features.csproj 
Microsoft.CodeAnalysis.Features.csproj
Microsoft.CodeAnalysis.Scripting.csproj
```

2023-08-01 20:28 UTC, tmat commented
These projects are fine in source build. I don't see any dependency on VS (note: `InternalsVisibleTo` does not add a dependency).
Besides, Features and Workspaces are needed for `dotnet watch`.

2023-08-01 22:05 UTC, beccamc commented
Ah, thank you Tomas! I was on auto-pilot just searching for the VS names. I didn't notice they were InternalsVisibleTo. It looks like we are okay to close this. Thanks for your help!

2023-08-01 22:05 UTC, closed without merging