Use raw strings in EditorFeatures tests
dotnet/roslyn pull request #69729
Opened 2023-08-26 03:25 UTC by CyrusNajmabadi

2023-08-26 03:30 UTC, CyrusNajmabadi commented on src/EditorFeatures/CSharpTest/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs
>          [WpfFact]
view with whitespace off.

2023-08-26 21:30 UTC, tmat requested changes
Could you please revert changes in EditAndContinue tests?

This would produce a lot of conflicts with my work in progress. We can apply the refactoring later.

2023-08-27 01:20 UTC, CyrusNajmabadi commented
Yup. Happy to.

2023-08-29 23:46 UTC, CyrusNajmabadi commented
@tmat enc changes reverted.

2023-08-30 03:26 UTC, tmat approved these changes

2023-08-30 03:32 UTC, merged