Fix the binlog version mismatch in 17.8
dotnet/roslyn pull request #71255
Opened 2023-12-13 23:52 UTC by Cosifne

Cherrypick from https://github.com/dotnet/roslyn/pull/71125

2023-12-13 23:53 UTC, dibarbet approved these changes

2023-12-14 01:17 UTC, jasonmalinowski approved these changes

2023-12-14 23:22 UTC, jasonmalinowski requested changes
Requesting change for the code itself, but the PR is linking to the wrong cherry-picked commit, so we should fix that before we confuse people.

2023-12-15 00:09 UTC, jasonmalinowski approved these changes

2023-12-15 05:17 UTC, merged