Preserve the whitespaces when rewriting an inheritdoc
dotnet/roslyn pull request #71589
Opened 2024-01-11 22:08 UTC by sdelarosbil

Fixes #67180 

I explain what's going on in my latest comment on the issue, but the basic idea is the newline between the summary opening tag and a code opening one gets lost during this parse which causes indentation changes since the original had the newline. As I was debugging this, it seemed the whole pipeline cared a lot about preserving whitespaces during (de)serialisation so this one seemed to have been a small oversight when inheritdoc became supported in QuickInfo.

2024-01-12 13:42 UTC, sharwell approved these changes

2024-01-12 13:45 UTC, sharwell requested changes
Can you add a new test here?
https://github.com/dotnet/roslyn/blob/main/src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests_Inheritdoc.vb

2024-01-12 20:29 UTC, sharwell commented
@sdelarosbil You currently have the derived type like this:

```cs
/// <summary>
/// <inheritdoc cref="BaseClass"/>
/// </summary>
```

You'll need to change it to this for reproducing the issue:

```cs
/// <inheritdoc cref="BaseClass"/>
```

2024-01-12 23:47 UTC, sdelarosbil commented
@sharwell done, it indeed works

2024-01-15 22:49 UTC, sdelarosbil commented
Odd, it seems the CI isn't passing for some reasons? It doesn't seem to the me or the test I just added. I opened another pr where everything passed so not sure what's happening.

2024-01-16 18:25 UTC, sharwell commented
@sdelarosbil Not sure how your change could impact that integration test. Will re-run it.

2024-01-16 18:25 UTC, sharwell commented
/azp run roslyn-integration-CI

2024-01-16 19:16 UTC, sharwell commented
/azp run roslyn-integration-corehost

2024-01-17 18:50 UTC, sharwell approved these changes

2024-01-17 18:50 UTC, merged