Skip the broken tests caused by editor
dotnet/roslyn pull request #71656
Opened 2024-01-16 18:46 UTC by Cosifne

These tests would fail after CI update to 17.9 P2. 
Test failures are caused because of new editor side feature. https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#auto-surround-with-quotes-or-brackets

I have filed bug on their side

2024-01-16 19:17 UTC, sharwell requested changes
Requesting that we disable the new surround with feature via build.ps1 (using vsregedit) instead of disabling these tests.

2024-01-16 22:15 UTC, sharwell approved these changes

2024-01-16 22:38 UTC, Cosifne commented
waiting Validation https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8928146&view=results

2024-01-16 22:48 UTC, jasonmalinowski approved these changes

2024-01-17 07:19 UTC, Cosifne commented
I get a passed run
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8930491&view=results

2024-01-17 07:19 UTC, merged