Include SourceLink file in CoreCompile dependency checks
dotnet/roslyn pull request #72109
Opened 2024-02-14 21:48 UTC by baronfel

A companion to https://github.com/dotnet/msbuild/pull/9743 to ensure that more sourcelink/determinism-related flags correctly cause the compiler to be invoked when they change

2024-02-14 22:18 UTC, rainersigwald requested changes
Apply to VB too please

https://github.com/dotnet/roslyn/blob/90cd6b600a7c982c0850c0b23e26b3783ee95477/src/Compilers/Core/MSBuildTask/Microsoft.VisualBasic.Core.targets#L6-L7

2024-02-14 22:29 UTC, baronfel commented
Thanks @rainersigwald - I've just done so.

2024-02-14 22:43 UTC, rainersigwald approved these changes

2024-02-16 16:36 UTC, baronfel commented
cc @jaredpar

2024-02-27 21:38 UTC, jaredpar approved these changes

2024-02-27 21:38 UTC, jaredpar commented
@dotnet/roslyn-compiler PTAL

2024-02-28 09:51 UTC, jjonescz approved these changes

2024-02-29 21:30 UTC, merged