Upgrade MicrosoftCodeAnalysisTestingVersion to 1.1.2-beta1.24121.1
dotnet/roslyn pull request #73840
Opened 2024-06-04 17:40 UTC by akhera99

Cherry-pick of https://github.com/dotnet/roslyn/pull/73831, with some additional error fixes.

2024-06-05 11:17 UTC, sharwell approved these changes

2024-06-06 19:49 UTC, arkalyanms approved these changes

2024-06-07 14:38 UTC, sharwell requested changes

2024-06-07 14:38 UTC, sharwell commented on src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj
> +    <TargetFrameworks>net7.0;net472</TargetFrameworks>
I don't see how we can make this change in the servicing branch. What limitation is causing the versions of packages outside the testing package to change?

2024-06-12 16:48 UTC, akhera99 commented
/azp run

2024-06-13 00:06 UTC, akhera99 commented
@dotnet-policy-service rerun

2024-06-13 00:09 UTC, JoeRobich approved these changes

2024-06-13 00:10 UTC, merged