Fix ref analysis of self-assignment
dotnet/roslyn pull request #75618
Opened 2024-10-24 08:59 UTC by jjonescz

Fixes https://github.com/dotnet/roslyn/issues/75592.

2024-10-24 09:16 UTC, jjonescz commented on src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
> +                """;
Without the fix, this compiled without an error.

2024-10-24 12:19 UTC, jaredpar requested changes
Think the error is in the wrong place here.

2024-10-24 12:19 UTC, jaredpar commented on src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
> +                        s.refField = ref s.field;
This is the code that should error as the _ref-safe-context_ is _return-only_.

2024-10-24 12:19 UTC, jaredpar commented on src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs
> +                S.M(ref s);
Consider that these two forms are equivalent 

```csharp
ref struct S {
  [UnscopedRef]
  void M1() { }

  static void M2([UnscopedRef] ref S p) { }
}

S local;
local.M1();
S.M2(ref local);
```

So if the `S.M(ref s)` is an error then virtually any instance method call on a `ref struct` with `[UnscopedRef]` is too..

2024-10-28 23:46 UTC, RikkiGibson approved these changes

2024-10-29 22:27 UTC, jaredpar approved these changes

2024-10-29 22:27 UTC, jaredpar commented on src/Compilers/CSharp/Test/Emit3/RefStructInterfacesTests.cs
> +                // (12,26): error CS8350: This combination of arguments to 'Program<S>.F1(ref S)' is disallowed because it may expose variables referenced by parameter 'x1' outside of their declarati
Can we add a variation of this test where the signature of `F1` is 

```csharp
static ref S F1(ref S x1)
```

2024-10-30 11:49 UTC, merged